/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as VerifyRouteImport } from './routes/verify'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CurationRouteImport } from './routes/curation'
import { Route as CreateLatexRouteImport } from './routes/create-latex'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ProfileIndexRouteImport } from './routes/profile/index'
import { Route as FilesIndexRouteImport } from './routes/files/index'
import { Route as FilesDocumentIdRouteImport } from './routes/files/$documentId'

const VerifyRoute = VerifyRouteImport.update({
  id: '/verify',
  path: '/verify',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CurationRoute = CurationRouteImport.update({
  id: '/curation',
  path: '/curation',
  getParentRoute: () => rootRouteImport,
} as any)
const CreateLatexRoute = CreateLatexRouteImport.update({
  id: '/create-latex',
  path: '/create-latex',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileIndexRoute = ProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesIndexRoute = FilesIndexRouteImport.update({
  id: '/files/',
  path: '/files/',
  getParentRoute: () => rootRouteImport,
} as any)
const FilesDocumentIdRoute = FilesDocumentIdRouteImport.update({
  id: '/files/$documentId',
  path: '/files/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/create-latex': typeof CreateLatexRoute
  '/curation': typeof CurationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/files/$documentId': typeof FilesDocumentIdRoute
  '/files': typeof FilesIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/create-latex': typeof CreateLatexRoute
  '/curation': typeof CurationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/files/$documentId': typeof FilesDocumentIdRoute
  '/files': typeof FilesIndexRoute
  '/profile': typeof ProfileIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/create-latex': typeof CreateLatexRoute
  '/curation': typeof CurationRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/verify': typeof VerifyRoute
  '/files/$documentId': typeof FilesDocumentIdRoute
  '/files/': typeof FilesIndexRoute
  '/profile/': typeof ProfileIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/create-latex'
    | '/curation'
    | '/login'
    | '/signup'
    | '/verify'
    | '/files/$documentId'
    | '/files'
    | '/profile'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/create-latex'
    | '/curation'
    | '/login'
    | '/signup'
    | '/verify'
    | '/files/$documentId'
    | '/files'
    | '/profile'
  id:
    | '__root__'
    | '/'
    | '/create-latex'
    | '/curation'
    | '/login'
    | '/signup'
    | '/verify'
    | '/files/$documentId'
    | '/files/'
    | '/profile/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CreateLatexRoute: typeof CreateLatexRoute
  CurationRoute: typeof CurationRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  VerifyRoute: typeof VerifyRoute
  FilesDocumentIdRoute: typeof FilesDocumentIdRoute
  FilesIndexRoute: typeof FilesIndexRoute
  ProfileIndexRoute: typeof ProfileIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/verify': {
      id: '/verify'
      path: '/verify'
      fullPath: '/verify'
      preLoaderRoute: typeof VerifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/curation': {
      id: '/curation'
      path: '/curation'
      fullPath: '/curation'
      preLoaderRoute: typeof CurationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/create-latex': {
      id: '/create-latex'
      path: '/create-latex'
      fullPath: '/create-latex'
      preLoaderRoute: typeof CreateLatexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/': {
      id: '/profile/'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/': {
      id: '/files/'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof FilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/files/$documentId': {
      id: '/files/$documentId'
      path: '/files/$documentId'
      fullPath: '/files/$documentId'
      preLoaderRoute: typeof FilesDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CreateLatexRoute: CreateLatexRoute,
  CurationRoute: CurationRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  VerifyRoute: VerifyRoute,
  FilesDocumentIdRoute: FilesDocumentIdRoute,
  FilesIndexRoute: FilesIndexRoute,
  ProfileIndexRoute: ProfileIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
