/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as MyFilesIndexRouteImport } from './routes/my-files/index'
import { Route as MyFilesDocumentIdRouteImport } from './routes/my-files/$documentId'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFilesIndexRoute = MyFilesIndexRouteImport.update({
  id: '/my-files/',
  path: '/my-files/',
  getParentRoute: () => rootRouteImport,
} as any)
const MyFilesDocumentIdRoute = MyFilesDocumentIdRouteImport.update({
  id: '/my-files/$documentId',
  path: '/my-files/$documentId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-files/$documentId': typeof MyFilesDocumentIdRoute
  '/my-files': typeof MyFilesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-files/$documentId': typeof MyFilesDocumentIdRoute
  '/my-files': typeof MyFilesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/my-files/$documentId': typeof MyFilesDocumentIdRoute
  '/my-files/': typeof MyFilesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/login' | '/signup' | '/my-files/$documentId' | '/my-files'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/login' | '/signup' | '/my-files/$documentId' | '/my-files'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/signup'
    | '/my-files/$documentId'
    | '/my-files/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
  MyFilesDocumentIdRoute: typeof MyFilesDocumentIdRoute
  MyFilesIndexRoute: typeof MyFilesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-files/': {
      id: '/my-files/'
      path: '/my-files'
      fullPath: '/my-files'
      preLoaderRoute: typeof MyFilesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/my-files/$documentId': {
      id: '/my-files/$documentId'
      path: '/my-files/$documentId'
      fullPath: '/my-files/$documentId'
      preLoaderRoute: typeof MyFilesDocumentIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
  MyFilesDocumentIdRoute: MyFilesDocumentIdRoute,
  MyFilesIndexRoute: MyFilesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
